services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db

  task-service:
    build:
      context: ./services/task-service
    container_name: task-service
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://task-service:3000
    depends_on:
      - task-service
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app

volumes:
  mongo-data:
