name: OWASP ZAP Scan

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose version

      - name: Create .env file from secrets
        run: |
          echo "PORT=3000" >> .env
          echo "MONGODB_URI=mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASS }}@mongodb:27017/testdb?authSource=admin" >> .env
          echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_USER }}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_PASS }}" >> .env
          echo "E2E_BASE_URL=http://localhost:3000" >> .env
          
      - name: Start target with Docker Compose
        run: |
          docker compose up -d --build

      - name: Wait for target app
        run: |
          for i in {1..10}; do
            curl -sf http://localhost:3000/tasks && break || sleep 3
          done

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'http://localhost:3000'
          fail_action: false
          artifact_name: zap_scan
          allow_issue_writing: false

      - name: Tear down services
        run: docker compose down -v
