name: OWASP ZAP Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up Docker Compose
        run: |
          docker compose version

      - name: Create .env file from secrets
        run: |
          echo "PORT=3000" >> .env
          echo "MONGODB_URI=mongodb://${{ secrets.MONGO_USER }}:${{ secrets.MONGO_PASS }}@mongodb:27017/testdb?authSource=admin" >> .env
          echo "MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_USER }}" >> .env
          echo "MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_PASS }}" >> .env

      - name: Start target with Docker Compose
        run: docker compose up -d --build

      - name: Wait for target app
        run: |
          for i in {1..10}; do
            curl -sf http://localhost:3000/tasks && break || sleep 3
          done

      - name: Run ZAP Baseline Scan with Docker
        run: |
          docker run --network host \
            -v $(pwd):/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://localhost:3000 -r report_html.html

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4.6.2
        with:
          name: zap-report
          path: report_html.html

      - name: Tear down services
        run: docker compose down -v
